window.__APP_CONFIG__ = {
  TAG_TEMPLATES: [
      { name: "velocity", defaultValue: 50, unit: "in/s" },
      { name: "pause", defaultValue: 1, unit: "seconds" },
      { name: "intake", defaultValue: 0, unit: "ticks/s" },
      { name: "autoAim", defaultValue: 0, unit: "" },
      { name: "shooterVelocity", defaultValue: 0, unit: "ticks/s" },
      { name: "hoodAngle", defaultValue: 0, unit: "degrees" },
      { name: "launchArtifacts", defaultValue: 1, unit: "seconds" }
  ],
  FIELD_SIZE_IN: 144,
  DEFAULT_CANVAS_SIZE: 720,
  DEFAULT_LEFT_PANEL_WIDTH: 420,
  DEFAULT_RIGHT_PANEL_WIDTH: 420,
  MIN_LEFT_PANEL_WIDTH: 240,
  MIN_RIGHT_PANEL_WIDTH: 240,
  GRID_DEFAULT_STEP: 24,
  GRID_MIN_STEP: 0.25,
  DEFAULT_SNAP_IN: 3,
  DEFAULT_TOLERANCE_IN: 5,
  DEFAULT_VELOCITY_IN_PER_S: 30,
  DEFAULT_PLAYBACK_SPEED_IN_PER_S: 30,
  DEFAULT_MAX_ACCEL_IN_PER_S2: 40,
  SPEED_PROFILE_SAMPLE_STEP_IN: 1,
  EPS: 0.000001,
  DEFAULT_ROBOT_DIMENSIONS: {
    length: 18,
    width: 18
  },
  POSE_POLL_INTERVAL_MS: 33,
  HUB_IP: "192.168.43.1",
  HUB_PORT: 8099,
  LIVE_POSE_SYNC_PREFIX: "init",
  UPLOAD_RESET_OK_MS: 1800,
  UPLOAD_RESET_FAIL_MS: 2200,
  PATH_SAMPLE_STEP_IN: 1,
  BEZIER_MIN_SAMPLES: 8,
  BEZIER_MAX_SAMPLES: 200,
  ARC_MAX_SAMPLES: 240,
  MIN_DRAW_SAMPLE_SPACING_IN: 0.25,
  MIN_DRAW_SEGMENT_LEN_IN: 0.5,
  DRAW_SIMPLIFY_TOLERANCE_IN: 0.2,
  PATH_COLOR: "#5cd2ff",
  START_COLOR: "#ffd166",
  WAYPOINT_COLOR: "#cbd5e1",
  LAST_POINT_COLOR: "#ffffff",
  FOOTPRINT_FILL: "#6be675",
  LIVE_POSE_FILL: "#ff6ad5",
  PREVIEW_FILL: "#94e2b8",
  DRAW_RAW_COLOR: "#94a3b8",
  DRAW_FIT_COLOR: "#38bdf8",
  DRAW_LABEL_FILL: "rgba(15,23,42,0.82)",
  DRAW_LABEL_STROKE: "rgba(255,255,255,0.8)",
  HUB_WS_PORT: 8000
};
